#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PYTHON_BIN="${PYTHON_BIN:-python3}"
STAMP="$(date +%Y%m%d_%H%M%S)"

export PYTHONUNBUFFERED=1
export ABLATION_OUTPUT_ROOT="${ABLATION_OUTPUT_ROOT:-results/ablation_stratified_paper_remote_${STAMP}}"

# Default to the groups that had not started on the local run when this script was made.
# Override with:
#   ABLATION_GROUPS=ga_hpo_dqn,ga_hpo_fe_dqn,fe_iddqn,iddqn,ga_hpo_iddqn
export ABLATION_GROUPS="${ABLATION_GROUPS:-fe_iddqn,iddqn,ga_hpo_iddqn}"
export ABLATION_SEEDS="${ABLATION_SEEDS:-42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61}"

export ABLATION_EVAL_SPLIT="${ABLATION_EVAL_SPLIT:-test}"
export ABLATION_FULL_TEST_EVAL="${ABLATION_FULL_TEST_EVAL:-1}"
export ABLATION_FULL_EVAL_MAX_STEPS="${ABLATION_FULL_EVAL_MAX_STEPS:-0}"

export ABLATION_MAX_WORKERS="${ABLATION_MAX_WORKERS:-8}"
export ABLATION_MAX_EPISODES="${ABLATION_MAX_EPISODES:-120}"
export ABLATION_MAX_STEPS_PER_EPISODE="${ABLATION_MAX_STEPS_PER_EPISODE:-1000}"
export ABLATION_VAL_EVAL_INTERVAL="${ABLATION_VAL_EVAL_INTERVAL:-10}"
export ABLATION_VAL_EVAL_EPISODES="${ABLATION_VAL_EVAL_EPISODES:-5}"

export ABLATION_GA_POPULATION_SIZE="${ABLATION_GA_POPULATION_SIZE:-8}"
export ABLATION_GA_GENERATIONS="${ABLATION_GA_GENERATIONS:-5}"
export ABLATION_GA_EVAL_EPISODES="${ABLATION_GA_EVAL_EPISODES:-3}"
export ABLATION_GA_MAX_WORKERS="${ABLATION_GA_MAX_WORKERS:-1}"

export ABLATION_HPO_TRIALS="${ABLATION_HPO_TRIALS:-20}"
export ABLATION_HPO_TIMEOUT="${ABLATION_HPO_TIMEOUT:-600}"
export ABLATION_HPO_EVAL_EPISODES="${ABLATION_HPO_EVAL_EPISODES:-3}"

export ABLATION_SEARCH_SPLIT="${ABLATION_SEARCH_SPLIT:-val}"
export ABLATION_SEARCH_STRATA_COLUMN="${ABLATION_SEARCH_STRATA_COLUMN:-balanced_workflow_stratum}"
export ABLATION_SEARCH_MAX_PROCESSES="${ABLATION_SEARCH_MAX_PROCESSES:-60}"
export ABLATION_SEARCH_MAX_TASKS="${ABLATION_SEARCH_MAX_TASKS:-1200}"
export ABLATION_SEARCH_MAX_STEPS="${ABLATION_SEARCH_MAX_STEPS:-200}"
export ABLATION_SEARCH_EVAL_EPISODES="${ABLATION_SEARCH_EVAL_EPISODES:-3}"

# 8 concurrent tasks x 4 torch threads ~= 32 CPU threads.
export ABLATION_TORCH_NUM_THREADS="${ABLATION_TORCH_NUM_THREADS:-4}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-4}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-4}"

export TRAIN_WORKFLOWS_PER_EPISODE="${TRAIN_WORKFLOWS_PER_EPISODE:-3}"
export EVAL_WORKFLOWS_PER_EPISODE="${EVAL_WORKFLOWS_PER_EPISODE:-5}"

echo "Output root: $ABLATION_OUTPUT_ROOT"
echo "Groups: $ABLATION_GROUPS"
echo "Seeds: $ABLATION_SEEDS"
echo "Workers: $ABLATION_MAX_WORKERS, torch threads/task: $ABLATION_TORCH_NUM_THREADS"

"$PYTHON_BIN" run_ablation_table.py

"$PYTHON_BIN" scripts/summarize_ablation_results.py --root "$ABLATION_OUTPUT_ROOT" || true
"$PYTHON_BIN" scripts/summarize_stratified_final_eval.py --root "$ABLATION_OUTPUT_ROOT" || true
